# Generated by Django 5.0.4 on 2024-04-10 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AbilityAssistWebApp', '0004_remove_userprofile_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='surname',
            new_name='last_name',
        ),
    ]
