# Generated by Django 5.0.4 on 2024-04-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AbilityAssistWebApp', '0005_remove_trips_user_trips_tripid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='tripID',
        ),
    ]
