# Generated by Django 5.0.4 on 2024-04-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbilityAssistWebApp', '0006_remove_trips_tripid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trips',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=2782911, max_length=10),
            preserve_default=False,
        ),
    ]
