# Generated by Django 5.0.4 on 2024-04-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AbilityAssistWebApp', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_name',
            new_name='surname',
        ),
    ]
