# Generated by Django 5.0.4 on 2024-05-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AbilityAssistWebApp', '0010_geolocation_contact_trip_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
