# Generated by Django 5.0.4 on 2024-05-04 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbilityAssistWebApp', '0011_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGeolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InitialGeolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
        migrations.AddField(
            model_name='trip',
            name='end_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AbilityAssistWebApp.finalgeolocation'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AbilityAssistWebApp.initialgeolocation'),
        ),
        migrations.DeleteModel(
            name='Geolocation',
        ),
    ]
