# Generated by Django 5.0.4 on 2024-05-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbilityAssistWebApp', '0012_finalgeolocation_initialgeolocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
