# Generated by Django 5.0.4 on 2024-05-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AbilityAssistWebApp', '0013_trip_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='canceled',
        ),
    ]
