# Generated by Django 5.0.4 on 2024-05-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbilityAssistWebApp', '0014_remove_trip_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AbilityAssistWebApp.finalgeolocation'),
        ),
    ]
