# Generated by Django 5.0.4 on 2024-05-13 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbilityAssistWebApp', '0015_alter_trip_end_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AbilityAssistWebApp.finalgeolocation'),
        ),
    ]
