# Generated by Django 5.0.4 on 2024-05-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbilityAssistWebApp', '0016_alter_trip_end_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
