# Generated by Django 5.0.4 on 2024-05-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbilityAssistWebApp', '0018_aboutimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialgeolocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
